// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLUdgiAkMI4ijyjY1uJTrgcv995Xwb-D0',
    appId: '1:81163687272:web:a998be96fbf32167c2f2dd',
    messagingSenderId: '81163687272',
    projectId: 'scalping-helper-app',
    authDomain: 'scalping-helper-app.firebaseapp.com',
    storageBucket: 'scalping-helper-app.firebasestorage.app',
    measurementId: 'G-9HXZTHEDHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg-PsBjnXZWy25gMnKNi0EffjZmXpehDg',
    appId: '1:81163687272:android:69c326e5a237d490c2f2dd',
    messagingSenderId: '81163687272',
    projectId: 'scalping-helper-app',
    storageBucket: 'scalping-helper-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrZlJ48sxe-0fHuckf__ETjmlyQyHad80',
    appId: '1:81163687272:ios:948e37bd7edb9c1cc2f2dd',
    messagingSenderId: '81163687272',
    projectId: 'scalping-helper-app',
    storageBucket: 'scalping-helper-app.firebasestorage.app',
    iosBundleId: 'com.example.scalpingHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrZlJ48sxe-0fHuckf__ETjmlyQyHad80',
    appId: '1:81163687272:ios:948e37bd7edb9c1cc2f2dd',
    messagingSenderId: '81163687272',
    projectId: 'scalping-helper-app',
    storageBucket: 'scalping-helper-app.firebasestorage.app',
    iosBundleId: 'com.example.scalpingHelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLUdgiAkMI4ijyjY1uJTrgcv995Xwb-D0',
    appId: '1:81163687272:web:0122ff17e0e59e4ac2f2dd',
    messagingSenderId: '81163687272',
    projectId: 'scalping-helper-app',
    authDomain: 'scalping-helper-app.firebaseapp.com',
    storageBucket: 'scalping-helper-app.firebasestorage.app',
    measurementId: 'G-LD0MPYESTZ',
  );
}
